name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        sudo apt-get update
        sudo apt-get install -y \
          python3-setuptools \
          python3-dev \
          libffi-dev \
          libssl-dev \
          autoconf \
          automake \
          libtool \
          build-essential \
          libncurses5-dev \
          pkg-config \
          zlib1g-dev \
          libltdl-dev \
          liblapack-dev \
          libblas-dev \
          gfortran \
          gcc \
          make \
          ccache \
          unzip \
          openjdk-8-jdk \
          zlib1g-dev \
          libncurses5-dev \
          libgmp-dev \
          clang \
          libc6 \
          libncurses5 \
          libstdc++6 \
          libz1 \
          build-essential \
          git \
          curl \
          wget

    - name: Install Android SDK and NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O android_cmdline_tools.zip
        unzip android_cmdline_tools.zip -d $HOME/android-sdk
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk;21.3.6528147"
      env:
        ANDROID_HOME: $HOME/android-sdk

    - name: Build APK
      run: |
        buildozer -v android debug
      env:
        ANDROID_HOME: $HOME/android-sdk

